### ISSUE TITLE
[Docs] Typo Error

### ISSUE THREAD

**Issue by sookyeongyeom** [noisrucer/girok#24]
## Description

README.md 오타 제보합니다.

### Location

🔗 [해당 부분 바로가기](https://github.com/noisrucer/girok#44-rmcat-command-)

![typo error](https://user-images.githubusercontent.com/98504939/227553011-08928e56-287a-462a-917b-082b34236fa9.png)

### After Fix

```
girok addcat Career/Dummy
```

**Comment by noisrucer** [comment]
@sookyeongyeom Thanks for your correction!
