### ISSUE TITLE
Password is limited to 30 characters

### ISSUE THREAD

**Issue by jeremyruppel** [noisrucer/girok#29]
## Bug Description

Girok looks slick! I went to register and received the following warning when my password was greater than the allowed characters. Girok let me register anyways and now I am unable to log in.

## Error Message

```
 [{'loc': ['body', 'password'], 'msg': 'ensure this value has at most 30 characters', 'type': 'value_error.any_str.max_length', 'ctx': {'limit_value': 30}}]
```

## Screenshots

<img width="1438" alt="Screen Shot 2023-03-29 at 9 29 48 AM" src="https://user-images.githubusercontent.com/251146/228554019-4337407b-7be0-4500-a46b-e6e8c929a782.png">

**Comment by noisrucer** [comment]
@jeremyruppel  Thanks for reporting the bug!

I just fixed the error and it should work okay now.

If you register again then it should work. Did you successfully register?

Thanks again :)

**Comment by jeremyruppel** [comment]
All set! Thanks for the quick fix!
