### ISSUE TITLE
Deadline options for chdate

### ISSUE THREAD

**Issue by coljac** [noisrucer/girok#30]
## Description

`girok chdate` should accept date shorthands as arguments rather than explicit date only. 

## Purpose

When creating a task, it's easy to set something to (for instance) today or tomorrow with `--tdy` and `--tmr`. But if I want to update a task with `girok chdate`, I can't pass these arguments or use shorthands like `girok chdate -d today`. This would be helpful when updating tasks.

**Comment by noisrucer** [comment]
Thanks for your suggestion!

I've added the extended group of deadline options for `chdate` command.

The options are the same as `addtask` command.
