### ISSUE TITLE
Add `girok done --force` or similar

### ISSUE THREAD

**Issue by coljac** [noisrucer/girok#31]
## Description
Allow marking of a task as done without responding to the `Are you sure y/N?` prompt.

## Purpose
When making aliases, cli tools, etc. it will be helpful to allow a task to be marked as done without responding to an interactive prompt, so explicitly overriding it when you are sure would be a useful feature, e.g `girok done 12 --yes`.

**Comment by noisrucer** [comment]
Thanks for your suggestion!

I've added `-y/--yes` option for `done`.

You can see the change after you upgrade.
