### ISSUE TITLE
Can I run it self-hosted?

### ISSUE THREAD

**Issue by johnnyutahh** [noisrucer/girok#36]
Current Readme says "Girok is running on AWS server [...]".

Can I run it self-hosted on my own server?

**Comment by 7ongxia** [comment]
I guess `Girok` uses AWS RDS to store users' data, so if u clone the repo and modify the code to connect to your own local RDS and run the server on your local Docker, it may run on your local RDS and Server.

**Comment by noisrucer** [comment]
I've been working on local storage(guest mode) for the past few days. The feature is now complete and will be released tonight!

Edit: You can upgrade the package to use guest mode now.
