### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by misraelson** [noisrucer/girok#37]
Running `pip3 install girok`
Get:
`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e689160>: Failed to establish a new connection: [Errno 9] Bad file descriptor')': /simple/girok/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e689610>: Failed to establish a new connection: [Errno 9] Bad file descriptor')': /simple/girok/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e6897f0>: Failed to establish a new connection: [Errno 9] Bad file descriptor')': /simple/girok/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e6899a0>: Failed to establish a new connection: [Errno 9] Bad file descriptor')': /simple/girok/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e689b50>: Failed to establish a new connection: [Errno 9] Bad file descriptor')': /simple/girok/
ERROR: Could not find a version that satisfies the requirement girok (from versions: none)
ERROR: No matching distribution found for girok`

**Comment by noisrucer** [comment]
Which operating system are you using?

**Comment by misraelson** [comment]
MacOS Big Sur. I wouldn't close this issue. My partner also tried installing on her Macbook and also got an error.

**Comment by misraelson** [comment]
Ok it worked this morning. There was some error over the weekend. Seems okay now 👍

**Comment by noisrucer** [comment]
I accidentally clicked "Close with comment" button :)

Okay that's great! 

Did you happen to figure out what was the issue?
