### ISSUE TITLE
Exclude the resources folder from the package

### ISSUE THREAD

**Issue by DerAndereJohannes** [noisrucer/girok#46]
## Description
Just installed Girok.

The Girok package itself is ~ 23MB in size when downloading and when it is on disk. Pretty much the entire application size is taken by the resources (`/site-packages/girok/resources`) folder which contains files that demo the application for the github page. The rest of the files total to 792KB.

Please consider excluding it to make the package an order of magnitude smaller.

Thanks!

**Comment by noisrucer** [comment]
Hi @DerAndereJohannes,

Thank you for the advice. You're right. I took a look at it and the gif and an image file do take up the most space. I should've taken them out.

Thank you so much!

**Comment by noisrucer** [comment]
Just updated the library :)

**Comment by DerAndereJohannes** [comment]
Awesome thanks for the fast response! Nice job! :-)
